apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dog-tinder-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: dog-tinder
  targetCPUUtilizationPercentage: 50
