apiVersion: v1
kind: Service
metadata:
  labels:
    service: dog-tinder
  name: dog-tinder-service
spec:
  type: NodePort
  ports:
  - name: dog-tinder-port
    port: 4000
    protocol: TCP
    targetPort: 4567
    nodePort: 30000
  selector:
    service: dog-tinder
    